const SYSTEM_ACTION_GET_CURRENT_STORE = 'system/getCurrentStore'
const SYSTEM_ACTION_SET_CURRENT_STORE = 'system/setCurrentStore'
const SYSTEM_ACTION_SET_CURRENT_STORE_ID = 'system/setCurrentStoreId'
const SYSTEM_ACTION_SET_LOGIN_STATUS = 'system/setLoginStatus'

export {
  SYSTEM_ACTION_GET_CURRENT_STORE,
  SYSTEM_ACTION_SET_CURRENT_STORE,
  SYSTEM_ACTION_SET_CURRENT_STORE_ID,
  SYSTEM_ACTION_SET_LOGIN_STATUS
}
