const SYSTEM_MUTATION_UPDATE_CURRENT_STORE = 'updateCurrentStore'
const SYSTEM_MUTATION_REVERSE_LOGIN_STATUS = 'reverseLoginStatus'
const SYSTEM_MUTATION_SET_LOGIN_STATUS = 'setLoginStatus'

export {
  SYSTEM_MUTATION_REVERSE_LOGIN_STATUS,
  SYSTEM_MUTATION_UPDATE_CURRENT_STORE,
  SYSTEM_MUTATION_SET_LOGIN_STATUS
}
